#!/bin/sh

set -e

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd)

echo ''
echo "dotfile: $DOTFILES_ROOT"
echo "pwd:     $(pwd)"
echo "home:    $HOME"
echo ''

bootstrap() {
    echo -e "\033[34m$1\033[0m"
    echo "  - $DOTFILES_ROOT/$1"
    BOOT="$1/bootstrap"
    if [ -x $BOOT ]; then
        echo "  - Found executable install script"
    else
        echo "  - No install script"
    fi
}

for i in $(ls -I '.gitignore' -I 'LICENSE' -I 'README.md' -I 'script'); do
    bootstrap $i
done
